#### Pavlo Yatluk
#### dz_43

### ЗАВДАННЯ

#### Застосуйте описані в лекції методи відбору ознак, використовуючи вже відомий вам датасет ірісів Фішера. Код для завантаження датасету: from sklearn import datasets iris = datasets.load_iris(). Прикріпіть посилання на файли на GitHub.

In [37]:
from sklearn.feature_selection import VarianceThreshold
import sklearn.datasets as sns
import pandas as pd

In [38]:
# загружаємо датасет

from sklearn import datasets
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [39]:
# визначаємо X та y

X = pd.DataFrame(iris['data'], columns=['sepal length', 'sepal width', 'petal length', 'petal width'])
print(X)                 
y = pd.DataFrame(iris['target'], columns=["target"])
print(y)

     sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
     target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]


In [20]:
X.shape

(1797, 64)

### Статистичний метод фільтрації ознак VarianceThreshold

In [22]:
# створюємо модель з пороговим значеннм дисперсії - 0,4

selector = VarianceThreshold(threshold=0.4)

In [23]:
# навчаємо модель

selector.fit_transform(X)

array([[ 0.,  5., 13., ...,  0.,  0.,  0.],
       [ 0.,  0., 12., ..., 10.,  0.,  0.],
       [ 0.,  0.,  4., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  1., 11., ...,  6.,  0.,  0.],
       [ 0.,  2., 10., ..., 12.,  0.,  0.],
       [ 0., 10., 14., ..., 12.,  1.,  0.]])

### Статистичний метод ознак фільтрації SelectKBest

In [40]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.datasets import load_digits

In [61]:
# визначаємо X та y

X = pd.DataFrame(iris['data'], columns=['sepal length', 'sepal width', 'petal length', 'petal width'])               
y = pd.DataFrame(iris['target'], columns=["target"])
X, y = load_digits(return_X_y=True)

In [62]:
# початкова кількість ознак

X.shape

(1797, 64)

In [27]:
# сторюємо та тренуємо модель з заданою кількістю ознак к=20

X_new = SelectKBest(f_classif, k=20).fit_transform(X,y)

C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [ 0 32 39] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw


In [28]:
# кінцева кількість ознак

X_new.shape

(1797, 20)

### Метод фільтрації ознак на основі ваг моделі - SelectFromModel

In [34]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [45]:
# визначаємо X та y

X = pd.DataFrame(iris['data'], columns=['sepal length', 'sepal width', 'petal length', 'petal width'])              
y = pd.DataFrame(iris['target'], columns=["target"])

In [46]:
# створюємо та тренуємо модель з пороговим значенням ваги - 0,2

sfm_selector = SelectFromModel(estimator=LogisticRegression(), threshold=0.2)
sfm_selector.fit(X, y)

C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pavel\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


SelectFromModel(estimator=LogisticRegression(), threshold=0.2)

In [47]:
# виводимо ознаки відібрані по параметру важливості

X.columns[sfm_selector.get_support()]

Index(['sepal length', 'sepal width', 'petal length', 'petal width'], dtype='object')

### Фільтрації ознак по методу головних компонент PCA

In [48]:
import numpy as np
from sklearn.decomposition import PCA

In [ ]:
# визначаємо Х

X = pd.DataFrame(iris['data'], columns=['sepal length', 'sepal width', 'petal length', 'petal width']) 

In [50]:
# створюємо та тренуємо модель

pca = PCA(n_components=2)
new_X = pca.fit_transform(X)

# нові отримані значення Х
new_X

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451],
       [-2.28085963,  0.74133045],
       [-2.82053775, -0.08946138],
       [-2.62614497,  0.16338496],
       [-2.88638273, -0.57831175],
       [-2.6727558 , -0.11377425],
       [-2.50694709,  0.6450689 ],
       [-2.61275523,  0.01472994],
       [-2.78610927, -0.235112  ],
       [-3.22380374, -0.51139459],
       [-2.64475039,  1.17876464],
       [-2.38603903,  1.33806233],
       [-2.62352788,  0.81067951],
       [-2.64829671,  0.31184914],
       [-2.19982032,  0.87283904],
       [-2.5879864 ,  0.51356031],
       [-2.31025622,  0.39134594],
       [-2.54370523,  0.43299606],
       [-3.21593942,  0.13346807],
       [-2.30273318,  0.09870885],
       [-2.35575405, -0.03728186],
       [-2.50666891, -0.14601688],
       [-2.46882007,  0.13095149],
       [-2.56231991,  0.36771886],
       [-2.63953472,

### Фільтрації ознак по методу сингулярного розкладання матриць (SVD)

In [52]:
from sklearn.decomposition import TruncatedSVD

In [53]:
# дані Х

X = pd.DataFrame(iris['data'], columns=['sepal length', 'sepal width', 'petal length', 'petal width']) 

In [54]:
# створюємо та тренуємо модель, вівидимо нові дані Х

svd =  TruncatedSVD(n_components = 2)
X_new = svd.fit_transform(X)
X_new

array([[ 5.91274714e+00,  2.30203322e+00],
       [ 5.57248242e+00,  1.97182599e+00],
       [ 5.44697714e+00,  2.09520636e+00],
       [ 5.43645948e+00,  1.87038151e+00],
       [ 5.87564494e+00,  2.32829018e+00],
       [ 6.47759822e+00,  2.32464996e+00],
       [ 5.51597520e+00,  2.07090423e+00],
       [ 5.85092859e+00,  2.14807482e+00],
       [ 5.15891972e+00,  1.77506408e+00],
       [ 5.64500117e+00,  1.99000106e+00],
       [ 6.26539771e+00,  2.42576813e+00],
       [ 5.75200785e+00,  2.02037338e+00],
       [ 5.48058085e+00,  1.97777558e+00],
       [ 4.95112411e+00,  2.04828749e+00],
       [ 6.52596417e+00,  2.91606081e+00],
       [ 6.79037199e+00,  2.82500759e+00],
       [ 6.27239468e+00,  2.60811578e+00],
       [ 5.92953789e+00,  2.26766614e+00],
       [ 6.64813130e+00,  2.38959506e+00],
       [ 6.09486463e+00,  2.36082303e+00],
       [ 6.25397363e+00,  2.12001187e+00],
       [ 6.07364677e+00,  2.27178150e+00],
       [ 5.36999813e+00,  2.49808604e+00],
       [ 6.

### Фільтрації ознак по методу лінійного дискримінантного аналізу (LDA)

In [55]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [57]:
# дані Х та у

X = pd.DataFrame(iris['data'], columns=['sepal length', 'sepal width', 'petal length', 'petal width'])              
y = pd.DataFrame(iris['target'], columns=["target"])

In [63]:
# # створюємо та тренуємо модель, вівидимо нові дані Х

lda = LinearDiscriminantAnalysis()
new_data = lda.fit_transform(X, y)
new_data

array([[-2.01463220e+00, -5.62348616e+00, -1.86594028e-01, ...,
        -1.09348511e-01, -1.83506669e-01,  9.65495420e-01],
       [ 2.20967396e-01,  3.59240033e+00,  2.14901657e+00, ...,
        -1.23115093e-01, -3.39210556e+00, -1.20766919e+00],
       [ 2.23485453e+00,  2.70950363e+00,  4.26992781e+00, ...,
         2.51256615e+00,  1.08370006e+00,  4.22490736e-03],
       ...,
       [-1.04697178e+00,  1.48367733e+00,  3.04170263e+00, ...,
         1.54913444e+00,  1.99315402e+00,  2.17737830e+00],
       [ 4.07872916e-01, -1.99167301e+00, -3.65835518e-01, ...,
         9.16595358e-01,  5.26856349e-01, -1.41509141e+00],
       [ 1.74145011e-01,  8.87174627e-01,  1.37776831e+00, ...,
        -5.14965352e-02,  3.18833067e+00,  6.91242304e-01]])